# Generated by Django 2.1.1 on 2019-11-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('projectName', models.CharField(max_length=200, null=True, unique=True, verbose_name='项目名称')),
                ('projectType', models.CharField(max_length=200, null=True, verbose_name='项目类型')),
                ('dept', models.CharField(max_length=200, null=True, verbose_name='所属部门')),
                ('code', models.CharField(max_length=500, null=True, verbose_name='项目编号')),
                ('productLine', models.CharField(max_length=200, null=True, verbose_name='IT部产品线')),
                ('status', models.BooleanField(default=1, verbose_name='项目状态')),
                ('projectCycle', models.CharField(max_length=200, null=True, verbose_name='项目周期')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '项目名称',
                'verbose_name_plural': '项目管理表',
                'db_table': 'project_manage',
                'ordering': ['created_time'],
            },
        ),
    ]
