# Generated by Django 2.1.1 on 2019-11-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='projectCycle',
        ),
        migrations.AddField(
            model_name='project',
            name='creator',
            field=models.CharField(max_length=200, null=True, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='project',
            name='projectEndTime',
            field=models.CharField(max_length=200, null=True, verbose_name='项目结束时间'),
        ),
        migrations.AddField(
            model_name='project',
            name='projectStartTime',
            field=models.CharField(max_length=200, null=True, verbose_name='项目开始时间'),
        ),
    ]
