# Generated by Django 2.1.1 on 2019-11-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0002_auto_20191117_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(max_length=5, null=True, verbose_name='项目状态'),
        ),
    ]
