# Generated by Django 2.1.1 on 2019-12-25 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('apiName', models.CharField(max_length=200, unique=True, verbose_name='接口名称')),
                ('apiPath', models.CharField(max_length=1024, verbose_name='接口地址')),
                ('apiDomain', models.CharField(max_length=512, verbose_name='域名或ip')),
                ('netProtocol', models.IntegerField(verbose_name='网络协议，0为http，1为https')),
                ('reqMethods', models.IntegerField(verbose_name='请求方式，0为get，1为post')),
                ('reqUa', models.CharField(max_length=200, null=True, verbose_name='域名或ip')),
                ('ownGroup', models.CharField(max_length=200, verbose_name='接口分组')),
                ('ownPro', models.CharField(max_length=200, unique=True, verbose_name='项目ID')),
                ('runStatus', models.IntegerField(default=0, verbose_name='接口执行状态，0：未执行，1：成功，2：失败')),
            ],
            options={
                'verbose_name': '接口名称',
                'verbose_name_plural': '接口名称',
                'db_table': 'api_manage',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ApiParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paramName', models.CharField(max_length=200, verbose_name='参数名称')),
                ('paramValue', models.CharField(max_length=200, null=True, verbose_name='参数值')),
                ('isForce', models.CharField(max_length=1, verbose_name='是否必选')),
                ('paramType', models.CharField(max_length=20, verbose_name='参数类型')),
                ('paramRemark', models.CharField(max_length=4096, null=True, verbose_name='参数注释，或实例')),
                ('ownApi', models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_params', to='apiManage.Api')),
            ],
            options={
                'verbose_name': '参数名称',
                'verbose_name_plural': '参数名称',
                'db_table': 'api_parameters',
                'ordering': ['id'],
            },
        ),
    ]
